env:
  global:
    - secure: "Uz21rM7B2gPZeE57lira+pyiQFblmD4x0GHFdnBESuzSAH5crz+6TLR/lxoa09mRx6CqqXOGIDXwbHAxg8LL3BEOm9sIL1bOXmZyTp9uiSbpCPXVBGSjOYUfRF3K3ohVys8w177uWgooQEdj0K+Z0PmzeMAuVEigSsDt1SEq0TeQXlUefv1WtqIj5LTX56QXN9h+/59UYnVmF0WXUWQ5FIMO0MsRkWP9v6BgDI5xD0HjH+50Um8w2Fn3AjWK0FbUxXpmUShZr/qeexMNk/q15jS5N6OwbTdSm9yu/8dUTxrcLM9AxQ3QZHOdjldBFsXroV62ItQzUaGTmfFZDgk67Yp//uTJ2grkIrTy2rddhrFHT34Qpsm2CppKdSO/GmXJokobE1rq0lcsT2YbHZwnSccH+MaCzMLCbY623in/6S1xk0HvMDPtVZpMYpBnV07/mf0PCWuLTkSAfN9oq0c2nz+0Lh7FuWoCsRTpC40tpBZctaLQdeNWSaM5QP5amrdLMarMR14MvteEwSfAyRw5vlYPb6bUWcyACtZFPZ5vJjMsqXeu66fQNlyzorwfNIrvYQW6ywysocBp2i5vMfmpwa4Chqfb9Ut946ZX274vIIFZKhLaLZ5WK7nJznmJWOIcwbbBAXWLc7tcN5c8hDbPq/symvoDANqMQq/2y67zkdM="
    - secure: "XeJm8GMgLuaOrLx2MzZkBUi5MwPh6Gc8PysV1DEBqtNj4mFHha4DnYy0eG/RCWnirr1l1j0qBA/NwjZYCibXHqMH02yHiJbhzlF/n/3HKG2olE8pG3zlIbuz0PRvEnH+mghI4uXGklcZapduWqjI+UgO6YK+y4YSgI7Dzd9535FPSxANFXDQq/U+nx9aNzm60MoiSFAVQj1dbG0K+G2N+iqX1uEvglWsYFSQHfUsF2WdC/WUZlemttHn+ASv9eVLZWJWpAvClc8pc8oe1N+kYA5NAoqQIcEKxzgFBUW+jcUaH7SSL5GqT0rjpWeO0GmE9yLMPVNzdI+96fhara8nFYL4zx8WPwDPsbkV+5QkxMe0HAiouR1siueoAqe55eWcxxRJ3c78m/f2nj+Wc+lYdRFifIi3FjCbPSTkqlJ9E4cxWEiR/28HILpy11QMNrH54T0fT5yNC8zYZXwmZ+G3yPx0DHBHIteYSWmzTPPubViSMtYWErotCuNXmWHZskRA/ZhzcJ/urB53URpROwcE8/PBU9JdMbWN9o+nSVl936PzDS1i1W4HW2FFEpPr/2RHYd5NhkyUtOwSCduY/omK9CA7K1E1yxdFZ7NIK9cI4UVoGdkOnXgqJxKby67XMcv6lhyaGvkbKYORZ/yikl9AzFXmY4Ul931QRzzKrQIVSzc="
    - secure: "Bfbwxj+H2Y6tdioU3m4/A4fvs03A9cZ9dVEZgxKoS7TMzgL3lqG+rnrJdbn8BAMcqsbktdWluVfDVJTMIEil5G7eAHwtfzEYJ+4RcyFAwt3FPrmF2McVqcUf5GLchaFJRlD7h+p3eiZ7ROLM0msixFO6LRcvZtNDlT/LSkZWM7gZZ97+VgkwwS+uF0/Dl6wGSZwIXBoM+skJ2oBmEl8tPy8ObYWdTr5aW6MOEkyteoS1cotlFlf1X3TdTE656uaDTXiaJUojQA1MUG1ckDnZoe4P3xCIvUh5cQQNqE//W5Y07l/yab0oHhKeeXIwh1CajiKqLzvEUuJVxtinO0AOaWYj51nPbyynytjLbU4YfUlkchRHb83yG5zgZa3lTVcWKM9L1pOOHGSIBRNMLe7tChVllq4IzgkLoeb3ulfFjQTr2t4g8292klqTxFH7QVY0aLeZLgfXKZusbSyJoo3tbDxwjhdAroBsZzBcm2Nd+E/O8rKejIvtk5POv4t2znICB1G5GUODRsRZ4EnTniCIO0u6/UOfJ1NEXt78krc7uRZ4bVY46HYOSUAUc57ZFvoVAx2rfoVSO6wRjrir4OeFS8WfJ7b0j6bCp+uw6eAdRzIXsAEc610Ktu/rNz3bvxS3B+m1TpJXsaDZ+tQHCEMMtuZLbOWMx8NIHu8+DxjZs1o="

language: python
python:
  - "3.6"
install:
  - pip install pipenv
  - pip install twine
  - pip install codacy-coverage
  - pipenv install
  - pipenv install --dev
script:
  - set -e
  - mypy --ignore-missing-imports .
  - pipenv run pytest -v -n 2 -s --cov=./
  - coverage xml
  - codecov -t $CODECOV_TOKEN
after_success:
  - pipenv run pipenv_to_requirements
  - python setup.py sdist bdist_wheel
  - if [ "$TRAVIS_BRANCH" = "dev" ]; then twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD --repository-url https://test.pypi.org/legacy/ dist/*; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*; fi
